import { translate } from '@docusaurus/Translate';
import { IntegrationsType } from "../types/integrations";
import {
    Search,
    Languages,
    Keyboard,
    Dark,
    ServerInfo,
    Responsive,
    Branding,
    Suspend,
    Upgrade,
    UserServer,
    UserIP,
    UserLogin,
    Firewall,
    SSL,
    ModSec,
    Factor,
    CPU,
    Box,
    IPblock,
    Terminal,
    AdminOff,
    Ports,
    Separate,
    WHMCS,
    API,
    Notifications,
    Services,
    Usage,
    Bolt,
    Configuration,
    Download,
    Domain,
    Folder,
    PHP,
    Python,
    WP,
    MySQL,
    ServerCog,
    CronJobs,
    Cache,
    DNS,
    Visitors,
    Activity,
    AccountCog,
    Apache,
    Nginx,
} from "./integration-icons";

export const integrations: IntegrationsType = {
    "ui-framework-packages": [
        {
            name: translate({ message: "Apache", id: "features.item.apache" }),
            icon: Apache,
            description: translate({ message: "Run Apache web server per user. Apache's support for .htaccess files enables users to customize and override global configuration settings on a per-directory basis.", id: "features.item.run_apache_web_serve" }),
            url: "/docs/articles/docker/how-to-set-nginx-apache-varnish-per-user-in-openpanel/#apache",
            status: "stable",
        },
        {
            name: translate({ message: "Nginx", id: "features.item.nginx" }),
            icon: Nginx,
            description: translate({ message: "Nginx web server is a lightweight, open-source solution. The OpenPanel version of the Nginx web server enables configuration of cache exclusion, cache purging, URL rewriting, and FastCGI cache on a per-domain basis.", id: "features.item.nginx_web_server_is" }),
            url: "/docs/articles/docker/how-to-set-nginx-apache-varnish-per-user-in-openpanel/#nginx",
            status: "stable",
        },
        {
            name: translate({ message: "OpenResty", id: "features.item.openresty" }),
            icon: Nginx,
            description: translate({ message: "OpenResty allows per-user customization by defining user-specific location blocks or dynamic Lua logic in the main config. Configuration is centralized and preloaded for performance ", id: "features.item.openresty_allows_per" }),
            url: "/docs/articles/docker/how-to-set-nginx-apache-varnish-per-user-in-openpanel/#openresty",
            status: "stable",
        },
        {
            name: translate({ message: "OpenLiteSpeed", id: "features.item.openlitespeed" }),
            icon: Apache,
            description: translate({ message: "OpenLiteSpeed is a high-performance, lightweight web server with built-in caching and .htaccess support. OpenPanel allows per-user configuration for security, caching, and rewrite rules.", id: "features.item.openlitespeed_is_a_h" }),
            url: "/docs/articles/docker/how-to-set-nginx-apache-varnish-per-user-in-openpanel/#openlitespeed",
            status: "stable",
        },
        {
            name: translate({ message: "Varnish", id: "features.item.varnish" }),
            icon: Nginx,
            description: translate({ message: "Varnish is a powerful HTTP accelerator designed for content-heavy websites. OpenPanel enables WordPress caching rules, purge logic, and backend configuration for optimal performance.", id: "features.item.varnish_is_a_powerfu" }),
            url: "/docs/articles/docker/how-to-set-nginx-apache-varnish-per-user-in-openpanel/",
            status: "stable",
         },
    ],
    "data-provider-packages": [
        {
            name: translate({ message: "Domain Names", id: "features.item.domain_names" }),
            icon: Domain,
            description: translate({ message: "Add domain names with automatic SSL renewals, include aliases and subdomains (Internationalized domains are supported), create redirects, enforce HTTPS, and edit vhost files.", id: "features.item.add_domain_names_wit" }),
            url: "/docs/panel/domains/",
            status: "stable",
        },
        {
            name: translate({ message: "File Manager", id: "features.item.file_manager" }),
            icon: Folder,
            description: translate({ message: "Effortlessly upload multiple files simultaneously without any upload limits. Edit files, adjust permissions, copy or move files, add new files, and perform various file management tasks.", id: "features.item.effortlessly_upload" }),
            url: "/docs/panel/files/",
            status: "stable",
        },
        {
            name: translate({ message: "PHP versions", id: "features.item.php_versions" }),
            icon: PHP,
            description: translate({ message: "Users can use different PHP versions for each domain, run multiple versions, set a default version for new domains, change limits by editing php.ini files.", id: "features.item.users_can_use_differ" }),
            url: "/docs/panel/php/domains/",
            status: "stable",
        },
        {
            name: translate({ message: "NodeJS and Python", id: "features.item.nodejs_and_python" }),
            icon: Python,
            description: translate({ message: "Effortlessly create and manage containerized NodeJS and Python applications. Proxy websites to display content from these applications seamlessly.", id: "features.item.effortlessly_create" }),
            url: "/docs/panel/applications/pm2/",
            status: "stable",
        },
        {
            name: translate({ message: "WP Manager", id: "features.item.wp_manager" }),
            icon: WP,
            description: translate({ message: "Automatic WordPress installer with features like auto-login to wp-admin, option editing, on-demand backup, debugging, and a variety of additional functionalities.", id: "features.item.automatic_wordpress" }),
            url: "/docs/panel/applications/wordpress/",
            status: "stable",
        },
        {
            name: translate({ message: "MySQL and phpMyAdmin", id: "features.item.mysql_and_phpmyadmin" }),
            icon: MySQL,
            description: translate({ message: "Create and manage MySQL databases and users easily. Automatically log in to phpMyAdmin, enable remote MySQL access, and adjust configuration settings with desired limits.", id: "features.item.create_and_manage_my" }),
            url: "/docs/panel/mysql/databases/",
            status: "stable",
        },
        {
            name: translate({ message: "SSL certificates", id: "features.item.ssl_certificates" }),
            icon: SSL,
            description: translate({ message: "Automatic SSL generation and renewal ensures that your website's security is effortlessly managed, providing continuous protection with up-to-date SSL certificates.", id: "features.item.automatic_ssl_genera" }),
            url: "/docs/panel/domains/SSL/",
            status: "stable",
        },
        {
            name: translate({ message: "Object Caching", id: "features.item.object_caching" }),
            icon: Cache,
            description: translate({ message: "Implement object caching using dedicated REDIS and Memcached instances. Set memory limits, start/stop services, and view logs efficiently.", id: "features.item.implement_object_cac" }),
            url: "/docs/panel/caching/",
            status: "stable",
        },
        {
            name: translate({ message: "Web Terminal", id: "features.item.web_terminal" }),
            icon: Terminal,
            description: translate({ message: "Run commands inside Docker containers easily with WebTerminal — a simple interface to access and manage containers directly from your browser.", id: "features.item.run_commands_inside" }),
            url: "/docs/panel/containers/terminal/",
            status: "stable",
        },
        {
            name: translate({ message: "Server settings", id: "features.item.server_settings" }),
            icon: Configuration,
            description: translate({ message: "Each user has complete control over their server configuration, enabling them to install or restart services, edit system configurations, and perform various other administrative tasks.", id: "features.item.each_user_has_comple" }),
            url: "/docs/panel/advanced/webserver_settings/",
            status: "stable",
        },
        {
            name: translate({ message: "Cron Jobs", id: "features.item.cron_jobs" }),
            icon: CronJobs,
            description: translate({ message: "Schedule and edit cronjobs directly from the OpenPanel interface to efficiently plan and manage scheduled actions.", id: "features.item.schedule_and_edit_cr" }),
            url: "/docs/panel/advanced/cronjobs/",
            status: "stable",
        },
        {
            name: translate({ message: "DNS Zone Editor", id: "features.item.dns_zone_editor" }),
            icon: DNS,
            description: translate({ message: "Easily edit DNS zone files for your domains and add various records such as A, AAAA, CNAME, MX, TXT, etc., through the OpenPanel interface.", id: "features.item.easily_edit_dns_zone" }),
            url: "/docs/panel/domains/dns/",
            status: "stable",
        },
        {
            name: translate({ message: "Resource usage", id: "features.item.resource_usage" }),
            icon: Usage,
            description: translate({ message: "Monitor real-time CPU and memory usage, check historical trends, and adjust server configuration as needed to optimize performance.", id: "features.item.monitor_real_time_cp" }),
            url: "/docs/panel/advanced/resource_usage/",
            status: "stable",
        },
        {
            name: translate({ message: "Visitor reports", id: "features.item.visitor_reports" }),
            icon: Visitors,
            description: translate({ message: "Access automatically generated, visually appealing visitor reports from your website's access logs. Explore visitor locations, accessed pages, IPs, error pages, and more with ease.", id: "features.item.access_automatically" }),
            url: "/docs/panel/domains/goaccess/",
            status: "stable",
        },
        {
            name: translate({ message: "Activity logs", id: "features.item.activity_logs" }),
            icon: Activity,
            description: translate({ message: "Every action in the OpenPanel interface is recorded, allowing users to easily track who did what and when, eliminating the need to sift through server logs.", id: "features.item.every_action_in_the" }),
            url: "/docs/panel/account/account_activity/",
            status: "stable",
        },
        {
            name: translate({ message: "Account settings", id: "features.item.account_settings" }),
            icon: AccountCog,
            description: translate({ message: "Users can change their email address and password, enable 2FA, adjust language preferences, and activate dark mode for a personalized experience.", id: "features.item.users_can_change_the" }),
            url: "/docs/panel/account/",
            status: "stable",
        },
    ],
    "community-data-provider-packages": [
        {
            name: translate({ message: "Simple server deployment", id: "features.item.simple_server_deploy" }),
            icon: Download,
            description: translate({ message: "Install OpenPanel in minutes. Provision new servers to your cluster with a single command.", id: "features.item.install_openpanel_in" }),
            url: "/docs/admin/intro/#installation",
            status: "stable",
        },
        {
            name: translate({ message: "Resource usage management", id: "features.item.resource_usage_manag" }),
            icon: CPU,
            description: translate({ message: "Limit the CPU, I/O bandwidth, IOPS, nproc and memory on a per-user basis to ensure consistent performance for all your hosted websites.", id: "features.item.limit_the_cpu__i_o_b" }),
            url: "/",
            status: "stable",
        },
        {
            name: translate({ message: "Switch web servers", id: "features.item.switch_web_servers" }),
            icon: Bolt,
            description: translate({ message: "With the Docker module, users have an option to switch to their preferred webserver: Nginx, Apache, OpenLitespeed, OpenResty.", id: "features.item.with_the_docker_modu" }),
            url: "/docs/panel/containers/webserver/",
            status: "stable",
        },
        {
            name: translate({ message: "Edit configuration", id: "features.item.edit_configuration" }),
            icon: Configuration,
            description: translate({ message: "Administrators have the capability to designate domains for panel access, modify ports, and edit settings for both the OpenPanel and OpenAdmin interfaces, providing flexibility in configuring the system to suit specific requirements.", id: "features.item.administrators_have" }),
            url: "/docs/category/settings/",
            status: "stable",
        },
        {
            name: translate({ message: "Resource usage statistics", id: "features.item.resource_usage_stati" }),
            icon: Usage,
            description: translate({ message: "Monitor CPU, Memory usage, Network, Disk and load with real time monitoring.", id: "features.item.monitor_cpu__memory" }),
            url: "/docs/admin/dashboard/#sse-usage",
            status: "stable",
        },
        {
            name: translate({ message: "Service management", id: "features.item.service_management" }),
            icon: Services,
            description: translate({ message: "Monitor services, initiate restarts, view logs, and perform additional management tasks efficiently from the admin interface.", id: "features.item.monitor_services__in" }),
            url: "/docs/admin/services/status/",
            status: "stable",
        },
        {
            name: translate({ message: "Smart Notifications", id: "features.item.smart_notifications" }),
            icon: Notifications,
            description: translate({ message: "Receive notifications for events such as reboots, high resource usage, website attacks, failed services, and other critical occurrences to stay informed about the status of your server.", id: "features.item.receive_notification" }),
            url: "/docs/admin/notifications/",
            status: "stable",
        },
        {
            name: translate({ message: "Terminal Commands", id: "features.item.terminal_commands" }),
            icon: Terminal,
            description: translate({ message: "OpenCLI serves as the terminal interface for Administrators, allowing automation of diverse OpenPanel settings with access to over 100 available commands.", id: "features.item.opencli_serves_as_th" }),
            url: "https://dev.openpanel.com/cli/commands.html",
            status: "stable",
        },
    ],
    frameworks: [
        {
            name: translate({ message: "Branding", id: "features.item.branding" }),
            icon: Branding,
            description: translate({ message: "Fully customise the OpenPanel with colours, logos, fonts and more that mirror the look and feel of your hosting company.", id: "features.item.fully_customise_the" }),
            url: "/docs/admin/settings/openpanel/#branding",
            status: "stable",
        },
        {
            name: translate({ message: "Fully responsive", id: "features.item.fully_responsive" }),
            icon: Responsive,
            description: translate({ message: "Access OpenPanel on desktop, tablet and mobile without any feature limitations.", id: "features.item.access_openpanel_on" }),
            url: "",
            status: "stable",
        },
        {
            name: translate({ message: "Dark Mode", id: "features.item.dark_mode" }),
            icon: Dark,
            description: translate({ message: "OpenPanel features a built-in dark mode that users can activate with a single click directly from the interface, enhancing user experience.", id: "features.item.openpanel_features_a" }),
            url: "/docs/panel/dashboard/dark-mode/",
            status: "stable",
        },
        {
            name: translate({ message: "Server Info", id: "features.item.server_info" }),
            icon: ServerInfo,
            description: translate({ message: "View real-time usage data, IP address, nameservers, and other important server information directly within the OpenPanel interface.", id: "features.item.view_real_time_usage" }),
            url: "/docs/panel/advanced/server_info/",
            status: "stable",
        },
        {
            name: translate({ message: "Advanced Search", id: "features.item.advanced_search" }),
            icon: Search,
            description: translate({ message: "Quickly and easily find what you are looking for with a powerful search functionality.", id: "features.item.quickly_and_easily_f" }),
            url: "/docs/panel/dashboard",
            status: "stable",
        },
        {
            name: translate({ message: "Multi-language support", id: "features.item.multi_language_suppo" }),
            icon: Languages,
            description: translate({ message: "OpenPanel is translation ready. Each login can view OpenPanel in their preferred language.", id: "features.item.openpanel_is_transla" }),
            url: "https://dev.openpanel.com/localization.html",
            status: "stable",
        },
        {
            name: translate({ message: "Keyboard Shortcuts", id: "features.item.keyboard_shortcuts" }),
            icon: Keyboard,
            description: translate({ message: "OpenPanel was designed with a focus on advanced users, offering over 20 keyboard shortcuts to enhance your navigation speed through the interface.", id: "features.item.openpanel_was_design" }),
            url: "/docs/articles/dev-experience/openadmin-keyboard-shortcuts/",
            status: "stable",
        },
    ],
    integrations: [
        {
            name: translate({ message: "Suspend / Delete accounts", id: "features.item.suspend___delete_acc" }),
            icon: Suspend,
            description: translate({ message: "Suspend customer accounts to instantly disable their OpenPanel access and websites. Delete accounts when they are no longer required.", id: "features.item.suspend_customer_acc" }),
            url: "/docs/admin/accounts/users/#suspend",
            status: "stable",
        },
        {
            name: translate({ message: "Upgrade / Downgrade package", id: "features.item.upgrade___downgrade" }),
            icon: Upgrade,
            description: translate({ message: "Seamlessly upgrade or downgrade a customer's package to another of your hosting packages.", id: "features.item.seamlessly_upgrade_o" }),
            url: "/docs/admin/accounts/users/#statistics",
            status: "stable",
        },
        {
            name: translate({ message: "Dedicated IP address", id: "features.item.dedicated_ip_address" }),
            icon: UserIP,
            description: translate({ message: "Allocate an IPv4 address to users, providing them with a dedicated IP for their websites and services.", id: "features.item.allocate_an_ipv4_add" }),
            url: "/docs/admin/accounts/users/#edit",
            status: "stable",
        },
        {
            name: translate({ message: "Impersonation", id: "features.item.impersonation" }),
            icon: UserLogin,
            description: translate({ message: "Auto-login to access a customer's account and see exactly what they see without having to leave your account.", id: "features.item.auto_login_to_access" }),
            url: "/docs/admin/accounts/users/#statistics",
            status: "stable",
        },
        {
            name: translate({ message: "Webserver per user", id: "features.item.webserver_per_user" }),
            icon: UserServer,
            description: translate({ message: "Administrators can select Apache, Nginx, OpenResty or OpenLitespeed as the default web server for new users. This flexibility allows admins to accommodate a mix of users utilizing Apache and others using Nginx, all within the same server.", id: "features.item.administrators_can_s" }),
            url: "/docs/articles/docker/how-to-set-nginx-apache-varnish-per-user-in-openpanel/",
            status: "stable",
        },
        {
            name: translate({ message: "Database server per user", id: "features.item.database_server_per" }),
            icon: UserServer,
            description: translate({ message: "Administrators can select either MySQL, Percona or MariaDB as the mysql server for each user. This flexibility allows admins to accommodate a mix of users utilizing MySQL and others using MariaDB, all within the same server.", id: "features.item.administrators_can_s" }),
            url: "/docs/articles/docker/how-to-set-mysql-mariadb-per-user-in-openpanel/",
            status: "stable",
        },
    ],
    "live-providers": [
        {
            name: translate({ message: "Containerized services", id: "features.item.containerized_servic" }),
            icon: Box,
            description: translate({ message: "Every user service is containerised. Containers have no access to other users or server files.", id: "features.item.every_user_service_i" }),
            url: "/docs/panel/intro/",
            status: "stable",
        },
        {
            name: translate({ message: "Resource limiting", id: "features.item.resource_limiting" }),
            icon: CPU,
            description: translate({ message: "Administrators have the ability to set specific limits per plan, including port speed, disk usage, inodes, the number of websites, MySQL databases, and domains.", id: "features.item.administrators_have" }),
            url: "/docs/admin/plans/hosting_plans/#create-a-plan",
            status: "stable",
        },
        {
            name: translate({ message: "SSL / TLS", id: "features.item.ssl___tls" }),
            icon: SSL,
            description: translate({ message: "Automatically provision and renewal of Let's Encrypt certificates.", id: "features.item.automatically_provis" }),
            url: "/docs/panel/domains/ssl/",
            status: "stable",
        },
        {
            name: translate({ message: "CorazaWAF", id: "features.item.corazawaf" }),
            icon: ModSec,
            description: translate({ message: "Administrators can activate CorazaWAF with a single click and configure the OWASP ruleset. Additionally, individual users have the flexibility to enable or disable WAF per domain or disable certain rules.", id: "features.item.administrators_can_a" }),
            url: "/docs/admin/security/waf/",
            status: "stable",
        },
        {
            name: translate({ message: "Firewall", id: "features.item.firewall" }),
            icon: Firewall,
            description: translate({ message: "Administrators can manage Sentinel - a fork of the ConfigServer Security & Firewall (CSF) directly from the admin interface. Only needed ports are open for users, and administrators have full control over them.", id: "features.item.administrators_can_m" }),
            url: "/docs/admin/security/firewall/",
            status: "stable",
        },
        {
            name: translate({ message: "ImunifyAV", id: "features.item.imunifyav" }),
            icon: Services,
            description: translate({ message: "OpenAdmin fully supports ImunifyAV.", id: "features.item.openadmin_fully_supp" }),
            url: "/docs/admin/security/imunify/",
            status: "stable",
        },
        {
            name: translate({ message: "Two-Factor Authentication", id: "features.item.two_factor_authentic" }),
            icon: Factor,
            description: translate({ message: "Users can enhance security by enabling Two-Factor Authentication for their OpenPanel account. Administrators have the flexibility to enforce or disable 2FA for any user.", id: "features.item.users_can_enhance_se" }),
            url: "/docs/panel/account/2fa/",
            status: "stable",
        },
       // {
       //     name: translate({ message: "Shell access DEPRECATED", id: "features.item.shell_access_depreca" }),
       //     icon: Terminal,
       //     description:
       //         "End users are restricted from root-level access to their container. Additionally, to increase security, all services within a user's container operate under distinct user accounts.",
       //     url: "/docs/panel/advanced/ssh/",
       //     status: "stable",
       // }, 
       // {
       //     name: translate({ message: "IP blocking DEPRECATED", id: "features.item.ip_blocking_deprecat" }),
       //     icon: IPblock,
       //     description:
       //         "Each user has the capability to configure a domain-specific IP block list, providing a personalized means to restrict access to websites by blocking specific IP addresses.",
       //     url: "",
       //    status: "stable",
       // },
        {
            name: translate({ message: "Disable admin panel", id: "features.item.disable_admin_panel" }),
            icon: AdminOff,
            description: translate({ message: "Administrators can effortlessly disable the OpenAdmin interface with a single click, while preserving the core functionality of OpenPanel.", id: "features.item.administrators_can_e" }),
            url: "/docs/admin/security/disable-admin/",
            status: "stable",
        },
        {
            name: translate({ message: "Separate services", id: "features.item.separate_services" }),
            icon: Separate,
            description: translate({ message: "Both OpenAdmin and OpenPanel employ separate databases and webservers, maintaining full independence from user websites.", id: "features.item.both_openadmin_and_o" }),
            url: "",
            status: "stable",
        },
        {
            name: translate({ message: "Custom ports", id: "features.item.custom_ports" }),
            icon: Ports,
            description: translate({ message: "Administrators have the flexibility to customize the default port (e.g., change from 2083) and alter the directory path (e.g., from /openpanel) to cater to specific preferences.", id: "features.item.administrators_have" }),
            url: "/docs/admin/settings/openpanel/",
            status: "stable",
        },
    ],
    "community-packages": [
        {
            name: translate({ message: "WHMCS", id: "features.item.whmcs" }),
            icon: WHMCS,
            description: translate({ message: "Integrate with the leading web hosting management and billing software.", id: "features.item.integrate_with_the_l" }),
            url: "/docs/articles/extensions/openpanel-and-whmcs/",
            status: "stable",
        },
        {
            name: translate({ message: "Blesta", id: "features.item.blesta" }),
            icon: WHMCS,
            description: translate({ message: "Provision OpenPanel accounts from blesta.", id: "features.item.provision_openpanel" }),
            url: "https://blesta.club/extensions/openpanel",
            status: "stable",
        },
        {
            name: translate({ message: "FOSSBilling", id: "features.item.fossbilling" }),
            icon: WHMCS,
            description: translate({ message: "Provision OpenPanel accounts from FOSSBilling software.", id: "features.item.provision_openpanel" }),
            url: "https://openpanel.com/docs/articles/extensions/openpanel-and-fossbilling/",
            status: "stable",
        },        
        {
            name: translate({ message: "API", id: "features.item.api" }),
            icon: API,
            description: translate({ message: "OpenAdmin API allows you to integrate with 3rd party systems you already use.", id: "features.item.openadmin_api_allows" }),
            url: "https://dev.openpanel.com/openadmin-api/",
            status: "stable",
        },
    ],
};
