# /etc/openpanel/caddy/check.conf

http://localhost {
   root * /etc/openpanel/caddy/domains/
   handle /check {
       map {query.domain} {bare_domain} {
           ~^www\.(.+)$ ${1}
           default       {query.domain}
       }

       @found file /{bare_domain}.conf
       respond @found 200
       respond 404
   }
}
