#MAIN:
(reverse_proxy_upstream) {
    reverse_proxy http://{args[0]}:{args[1]} {
        header_up Host {host}
        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-For {remote_host}
        header_up X-Forwarded-Proto {scheme}
        transport http {
            keepalive 30s
            keepalive_idle_conns 20
        }
    }
}

#PER DOMAIN:
<DOMAIN_NAME>, www.<DOMAIN_NAME> {

    # logging
    import domain_log <DOMAIN_NAME>

    # compress
    encode zstd gzip {
        minimum_length 1024
    }

    route {

        # redirects
        import /etc/openpanel/caddy/redirects.conf
    
        # waf
        coraza_waf {
            load_owasp_crs
            directives `
                Include /etc/openpanel/caddy/coraza_rules.conf
                Include /etc/openpanel/caddy/coreruleset/crs-setup.conf.example
                Include /etc/openpanel/caddy/coreruleset/rules/*.conf
                SecRuleEngine Off
                SecAuditEngine RelevantOnly
                SecRuleRemoveById 007
                SecRuleRemoveByTag example
                SecAuditLog /var/log/caddy/coraza_waf/<DOMAIN_NAME>.log
                SecAuditLogParts AHFZ
                SecAuditLogFormat json
            `
        }

        # user webserver
        import reverse_proxy_upstream 127.0.0.1 <NON_SSL_PORT>
    }

    tls {
        on_demand
    }
}
