The free version of OpenPanel was released exactly 3 months ago, and we now have over 500 active installs! Thank you all for trying OpenPanel and for your suggestions and contributions.

In these 3 months, we've released 5 updates, added support for Debian, created a WHMCS module, translated to 3 languages, and much more.
We are now proud to announce the release of **OpenPanel Enterprise version**.

We hope to release the product by the end of the month, but please note that not all features for the Pro version will be immediately available; it will take several months for all planned features to be implemented.

There will be two product versions:
1. **Community Edition** - Free version
2. **Enterprise Edition** - Paid version with monthly, yearly, and a lifetime plan (this year only).

### Pricing Options:
- **Monthly Plan**: $19.95 per month with a price-lock guarantee.
- **Yearly Plan**: $192 per year (20% savings).
- **Lifetime Plan**: $248.

The free version will retain all existing features and continue to receive regular updates. It will include:
- All existing features.
- Monthly updates.
- Support via forums/Discord.

### Premium Version Includes:
- **White-Labeling**: Options to completely brand the panel as your own.
- **Billing Integrations**: WHMCS, Blesta, HostBill, FossBilling.
- **Auto-Installers**: 50+ CMS and tools.
- **Additional Pro Features**: Emails, FTP, clustering, Cloudflare DNS.
- **Migration Tools**: cPanel2OpenPanel and WordPress2OpenPanel.
- **Backup Storage**: 100GB of backup storage.
- **Real-Time Updates**: Immediate bug fixes as soon as they are available.
- **On-Site Support**: TeamViewer/AnyDesk support.

All paid options include support from our team: installation support, integration of third-party tools, and hands-on support via TeamViewer/AnyDesk.

For hosting providers, we also offer white-label tutorials for your blog/knowledgebase and support ticket options. When clients have technical questions or issues related to OpenPanel, you can direct-message our developers for answers or resolutions with a 30-minute SLA.

The Lifetime Plan will be available only this year and is intended to help us accelerate the development of features for the Pro version.

For full feature comparison and purchasing options please view: https://openpanel.co/enterprise

