---
title: OpenPanel Enterprise
description: OpenPanel Enterprise edition
slug: openpanel-enterprise-version
authors: stefanpejcic
tags: [OpenPanel, news, version]
image: https://openpanel.co/img/blog/openpanel_enterprise.png
hide_table_of_contents: true
is_featured: true

---

OpenPanel Enterprise edition

<!--truncate-->



At the time of writing *(July 2024), the free version of OpenPanel was released just 3 months ago, and we are excited to have crossed the 100 active installs treshold! Thank you all for trying OpenPanel and for your suggestions and contributions.

In these 3 months, we've released 6 updates, added support for Debian, created a WHMCS module, translated to 4 languages, and much more.
We are now proud to announce the release of **OpenPanel Enterprise version**.

We hope to release the **OpenPanel 0.2.2** - the first premium version of the panel, by the end of the month, but please note that not all features for the Pro version will be immediately available; it will take several months for all planned features to be implemented.

There will be two product versions:
1. **Community Edition** - Free version
2. **Enterprise Edition** - Paid version with monthly, yearly, and a lifetime plan (this year only).

### Pricing Options:
- [**Monthly Plan**: 14,95 EUR per month with a price-lock guarantee.](https://my.openpanel.co/index.php?rp=/store/openpanel/enterprise-license)
- **Yearly Plan**: 149,50 EUR per year (20% savings).
- [**Lifetime Plan**:  269,19 EUR.](https://my.openpanel.co/index.php?rp=/store/openpanel/lifetime-enterprise-license)

The free version will retain all existing features and continue to receive regular updates. It will include:
- All existing features.
- Monthly updates.
- Support via forums/Discord.

### Premium Version Includes:
- **White-Labeling**: Options to completely brand the panel as your own.
- **Billing Integrations**: WHMCS, Blesta, HostBill, FossBilling.
- **Auto-Installers**: 50+ CMS and tools.
- **Additional Pro Features**: Emails, FTP, clustering, Cloudflare DNS.
- **Migration Tools**: cPanel-2-OpenPanel and WordPress-2-OpenPanel.
- **Backup Storage**: 100GB of backup storage.
- **Real-Time Updates**: Immediate bug fixes as soon as they are available.
- **On-Site Support**: TeamViewer/AnyDesk support.

All paid options include support from our team: installation support, integration of third-party tools, and hands-on support via TeamViewer/AnyDesk.

For hosting providers, we also offer white-label tutorials for your blog/knowledgebase and support ticket options. When clients have technical questions or issues related to OpenPanel, you can direct-message our developers for answers or resolutions with a 30-minute SLA.

The Lifetime Plan will be available only this year and is intended to help us accelerate the development of features for the Pro version.

For full feature comparison and purchasing options please view: https://openpanel.co/beta

