---
title: OpenPanel now supports all major RHEL distributions
description: OpenPanel now supports all major RHEL Distributions: AlmaLinux, Fedora, RockyLinux and CentOS
slug: openpanel-rhel-support
authors: stefanpejcic
tags: [OpenPanel, news, version]
image: https://openpanel.co/img/blog/openpanel_enterprise.png
hide_table_of_contents: true
is_featured: true

---

OpenPanel now supports all major RHEL Distributions: AlmaLinux, Fedora, RockyLinux and CentOS

<!--truncate-->
