/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const mainSidebar = {
   panel: [
    { type: 'autogenerated', dirName: 'panel' },
    {
        type: "link",
        href: "https://community.openpanel.org",
        label: "Join our Community",
        className: "enterprise-badge",
    }
  ],   
  admin: [
    { type: 'autogenerated', dirName: 'admin' },
    // Promo
    {
      type: 'link',
      href: 'https://dev.openpanel.com',
      label: 'Developer Docs',
      className: 'enterprise-badge',
    },
  ],

  articles: [
    { type: 'autogenerated', dirName: 'articles' },
    // Promo
    {
      type: 'link',
      href: 'https://dev.openpanel.com',
      label: 'Developer Docs',
      className: 'enterprise-badge',
    },
  ],
  changelog: [
    { type: 'autogenerated', dirName: 'changelog' },
    // Promo
    {
      type: 'link',
      href: '/roadmap',
      label: 'Product Roadmap',
      className: 'enterprise-badge',
    },
  ],
};

module.exports = mainSidebar;
